name: metaworld_multitask_part3

task_name: ${name}

tasks:
  - peg-unplug-side
  - window-open
  - window-close
  - reach
  - handle-pull-side
  - plate-slide
  - plate-slide-back
  - plate-slide-back-side
  - plate-slide-side

shape_meta: &shape_meta
  obs:
    point_cloud:
      shape: [512, 3]
      type: point_cloud
    agent_pos:
      shape: [9]
      type: low_dim
  action:
    shape: [4]

env_runner:
  _target_: mp1.env_runner.metaworld_multitask_runner.MultiMetaworldRunner
  eval_episodes: 20
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  fps: 10
  n_envs: null
  n_train: null
  n_test: null
  task_names: ${task.tasks}
  device: ${training.device}
  use_point_crop: ${policy.use_point_crop}

dataset:
  _target_: mp1.dataset.metaworld_multitask_dataset.MultiMetaworldDataset
  tasks:
    - name: peg-unplug-side
      zarr_path: data/metaworld_peg-unplug-side_expert.zarr
    - name: window-open
      zarr_path: data/metaworld_window-open_expert.zarr
    - name: window-close
      zarr_path: data/metaworld_window-close_expert.zarr
    - name: reach
      zarr_path: data/metaworld_reach_expert.zarr
    - name: handle-pull-side
      zarr_path: data/metaworld_handle-pull-side_expert.zarr
    - name: plate-slide
      zarr_path: data/metaworld_plate-slide_expert.zarr
    - name: plate-slide-back
      zarr_path: data/metaworld_plate-slide-back_expert.zarr
    - name: plate-slide-back-side
      zarr_path: data/metaworld_plate-slide-back-side_expert.zarr
    - name: plate-slide-side
      zarr_path: data/metaworld_plate-slide-side_expert.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.02
  max_train_episodes: 90
