name: metaworld_multitask_part2

task_name: ${name}

tasks:
  - sweep
  - soccer
  - peg-insert-side
  - hammer
  - coffee-push
  - box-close
  - bin-picking

shape_meta: &shape_meta
  obs:
    point_cloud:
      shape: [512, 3]
      type: point_cloud
    agent_pos:
      shape: [9]
      type: low_dim
  action:
    shape: [4]

env_runner:
  _target_: mp1.env_runner.metaworld_multitask_runner.MultiMetaworldRunner
  eval_episodes: 20
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  fps: 10
  n_envs: null
  n_train: null
  n_test: null
  task_names: ${task.tasks}
  device: ${training.device}
  use_point_crop: ${policy.use_point_crop}

dataset:
  _target_: mp1.dataset.metaworld_multitask_dataset.MultiMetaworldDataset
  tasks:
    - name: sweep
      zarr_path: data/metaworld_sweep_expert.zarr
    - name: soccer
      zarr_path: data/metaworld_soccer_expert.zarr
    - name: peg-insert-side
      zarr_path: data/metaworld_peg-insert-side_expert.zarr
    - name: hammer
      zarr_path: data/metaworld_hammer_expert.zarr
    - name: coffee-push
      zarr_path: data/metaworld_coffee-push_expert.zarr
    - name: box-close
      zarr_path: data/metaworld_box-close_expert.zarr
    - name: bin-picking
      zarr_path: data/metaworld_bin-picking_expert.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.02
  max_train_episodes: 90
